platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application
        attrs:
          android:requestLegacyExternalStorage: "true"
          # xmlns:tools: "http://schemas.android.com/tools"
          # tools:replace: "android:usesCleartextTraffic"

      - file: AndroidManifest.xml
        target: manifest
        merge:
          <manifest>
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
          </manifest>
    xml:
      - resFile: values/styles.xml
        target: resources/style[@name="AppTheme.NoActionBar"]
        merge: 
          <style name="AppTheme.NoActionBar" parent="Theme.AppCompat.DayNight.NoActionBar">
            <item name="android:windowFullscreen">true</item>
          </style>
