name: Build source code and send to Capgo
on:
  push:
    tags:
      - '*'
      
jobs:
  deploy:
    if: "contains(github.event.head_commit.message, 'prod')"
    runs-on: ubuntu-latest
    name: "Build code and release"
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install dependencies
        id: install_code
        run: npm i
      - name: Build
        id: build_code
        run: npm run build
      - name: Create Release
        id: create_release
        run: npx @capgo/cli@latest upload -a ${{ secrets.CAPGO_TOKEN }} -c production
